"""
Handle the code generation process.
It takes the IR generated by the parser and use the classes defined in op.py to produce the final code.
It contains generic functions not related to exact output language
"""
import logging
import os
import pickle
import re
from collections import OrderedDict
from copy import copy
from typing import TYPE_CHECKING

import jsonpickle  # type: ignore[import-untyped]
from lark import lark

from masm2c import op
from masm2c.enumeration import IndirectionType
from masm2c.Token import Expression, Token as Token_
from masm2c.pgparser import TopDownVisitor

if TYPE_CHECKING:
    from masm2c.proc import Proc
    from masm2c.parser import Parser


class Gen(TopDownVisitor):
    def __init__(self, context: "Parser", outfile: str = "", merge_data_segments: bool = True) -> None:
        self._context = context
        self._namespace: str = ""
        self.label_to_proc: dict[str, str] = {}
        self._isjustlabel = False
        self.groups: OrderedDict[str, str] = OrderedDict()
        self.grouped: set[str] = set()
        self._middle_size = 0
        self.merge_data_segments = merge_data_segments
        self._procs = context.proc_list
        self.body: str = ""
        self.lea = False
        self._work_segment = "ds"
        self.isvariable = False  # only address or variable
        self._warned_segment_overwrites: set[str] = set()
        self._warned_struct_overwrites: set[str] = set()

        self.dispatch: str = ""
        self.prefix: str = ""
        self._cmdlabel: str = ""


    def calculate_size(self, expr: Expression) -> int:
        size = expr.size()
        if size:
            return size
        if expr.indirection == IndirectionType.POINTER:
            label_size = self._pointer_alias_size(expr)
        else:
            label_size = self._symbolic_label_size(expr)
        if label_size:
            return label_size
        from masm2c.parser import ExprSizeCalculator, Vector

        return ExprSizeCalculator(init=Vector(0, 0), context=self._context).visit(expr).values[0]

    def _symbolic_label_size(self, node) -> int:
        if isinstance(node, Expression):
            return max((self._symbolic_label_size(child) for child in node.children), default=0)
        if isinstance(node, lark.Tree):
            if node.data in {"register", "segmentregister"} and node.children:
                return self._context.register_size(str(node.children[0]))
            return max((self._symbolic_label_size(child) for child in node.children), default=0)
        if isinstance(node, list):
            return max((self._symbolic_label_size(child) for child in node), default=0)
        if getattr(node, "type", None) != "LABEL":
            return 0
        symbol = self._context.symbols.get_global(node)
        if not isinstance(symbol, (op._assignment, op._equ)) or not isinstance(symbol.value, Expression):
            return 0
        return (
            symbol.value.size()
            or symbol.value.ptr_size
            or symbol.value.element_size
            or self._symbolic_label_size(symbol.value)
        )

    def _pointer_alias_size(self, node) -> int:
        if isinstance(node, (Expression, lark.Tree)):
            return max((self._pointer_alias_size(child) for child in node.children), default=0)
        if isinstance(node, list):
            return max((self._pointer_alias_size(child) for child in node), default=0)
        if getattr(node, "type", None) != "LABEL":
            return 0
        symbol = self._context.symbols.get_global(node)
        if not isinstance(symbol, (op._assignment, op._equ)) or not isinstance(symbol.value, Expression):
            return 0
        return symbol.value.ptr_size


    def _calculate_struct_alias_member_size(self, struct_type: str, alias: str, seen: set[str] | None = None) -> int:
        seen = seen or set()
        alias = alias.lower()
        if alias in seen:
            return 0
        seen.add(alias)
        struct = self._context.symbols.get_global(struct_type)
        alias_symbol = self._context.symbols.get_global(alias)
        if not isinstance(struct, op.Struct) or not isinstance(alias_symbol, (op._equ, op._assignment)):
            return 0
        if not isinstance(alias_symbol.value, Expression):
            return alias_symbol.size
        referenced_labels = Token_.find_tokens(alias_symbol.value, "LABEL") or []
        for referenced_label in referenced_labels:
            referenced_name = str(referenced_label).lower()
            try:
                return struct.getitem(referenced_name).getsize()
            except KeyError:
                if size := self._calculate_struct_alias_member_size(struct_type, referenced_name, seen):
                    return size
        return alias_symbol.size

    def _calculate_known_struct_member_size(self, member: str) -> int:
        for struct_name, symbol in self._context.symbols.get_globals().items():
            if not isinstance(symbol, op.Struct):
                continue
            try:
                return symbol.getitem(member).getsize()
            except KeyError:
                if size := self._calculate_struct_alias_member_size(struct_name, member):
                    return size
        return 0

    def infer_struct_type_for_member(self, member: str) -> str:
        matches: list[str] = []
        member = member.lower()
        for struct_name, symbol in self._context.symbols.get_globals().items():
            if not isinstance(symbol, op.Struct):
                continue
            try:
                symbol.getitem(member)
                matches.append(struct_name)
            except KeyError:
                if self._calculate_struct_alias_member_size(struct_name, member):
                    matches.append(struct_name)
        return matches[0] if len(matches) == 1 else ""

    def calculate_member_size(self, label: list[str]) -> int:
        """
        Calculate the size of a member.

        :param label: The label of the member
        :return: The size of the member
        """
        g = self._context.symbols.get_global(label[0])
        if g is None:
            return 0
        type = label[0] if isinstance(g, op.Struct) else g.original_type

        try:
            for member in label[1:]:
                if (g := self._context.symbols.get_global(type)) is None:
                    raise KeyError(type)
                if isinstance(g, op.Struct):
                    try:
                        g = g.getitem(member)
                    except KeyError:
                        if size := self._calculate_struct_alias_member_size(type, member):
                            return size
                        raise
                    type = g.data  # type: ignore[union-attr]
                else:
                    return g._size
        except KeyError as ex:
            logging.debug("Didn't found for %s %s will try workaround", label, ex.args)
            # If members are global as with M510 or TASM, use that. Otherwise
            # infer from any known struct member with this name.
            g = self._context.symbols.get_global(label[-1])
            if g is None or getattr(g, "size", 0) == 0:
                return self._calculate_known_struct_member_size(label[-1])

        return g.size if g is not None else 0



    def leave_unique_labels(self, labels):
        """For IDA .lst it takes a list of labels and returns a list of unique labels based on address.

        :param labels: a list of labels to be processed
        :return: A list of labels.
        """
        if not self._context.is_listing_source():
            return labels
        uniq_labels = OrderedDict()
        for label in labels:
            g = self._context.symbols.get_global(label)
            uniq_labels[f"{g.real_seg}_{g.real_offset}"] = label
        return uniq_labels.values()

    def merge_procs(self):
        """Merge procs in case they have cross jumps since incompatible with C.

        :return:
        """
        #if self._context.args.mergeprocs == "separate":
        #    self._link_consecutive_non_terminated_procs()

        self.generate_label_to_proc_map()

        #if self._context.args.mergeprocs == 'separate':

        if self._context.args.get("mergeprocs") != "single":
            self._prepare_non_single_proc_data()

            self._align_grouping_lists()
            self._leave_only_same_segment_procs()
            self.print_how_procs_merged()

        self._merge_all_procs()

    def _merge_all_procs(self):
        groups = []
        #groups_id = 1
        for first_proc_name in self._procs:
            if first_proc_name in self.grouped:
                continue
            first_proc = self._context.symbols.get_global(first_proc_name)
            if self._context.args.get("mergeprocs") == "single" or first_proc.to_group_with:
                    groups = self.merge_all_procs_related_to_this(first_proc_name, first_proc, groups, len(groups) + 1)
        self._procs = [x for x in self._procs if x not in self.grouped]
        self._procs += groups
        self._procs = self.sort_procedure_list_in_linenumber_order(self._procs)

    def merge_all_procs_related_to_this(self, first_proc_name: str, first_proc: "Proc", groups: list[str], groups_id: int) -> list[str]:
        from masm2c.proc import Proc
        logging.debug("Merging %s", first_proc_name)
        new_group_name = f"_group{groups_id}"
        first_label = op.label(first_proc_name, proc=new_group_name, isproc=False,
                               line_number=first_proc.line_number, far=first_proc.far)
        first_label.real_offset, first_label.real_seg = first_proc.real_offset, first_proc.real_seg
        first_label.used = True

        first_proc.stmts.insert(0, first_label)
        first_proc.provided_labels.add(first_proc_name)
        self._context.symbols.reset_global(first_proc_name, first_label)
        self.grouped.add(first_proc_name)
        self.groups[first_proc_name] = new_group_name
        assert self._context.args
        proc_to_group = self._procs if self._context.args.get("mergeprocs") == "single" else first_proc.to_group_with
        proc_to_group = self.sort_procedure_list_in_linenumber_order(proc_to_group)
        for next_proc_name in proc_to_group:
            if next_proc_name == first_proc_name or next_proc_name in self.grouped\
                or not (next_proc := self._context.symbols.get_global(next_proc_name)) or not isinstance(next_proc, Proc):
                continue
            self.merge_two_procs_with_label(first_proc_name, first_proc, next_proc_name, next_proc,
                                            new_group_name)
        groups += [new_group_name]
        self._context.symbols.set_global(new_group_name, first_proc)
        #groups_id += 1
        return groups

    def merge_two_procs_with_label(self, first_proc_name: str, first_proc: "Proc", next_proc_name: str, next_proc: "Proc", new_group_name: str):
        self.groups[next_proc_name] = new_group_name
        next_label = op.label(next_proc_name, proc=first_proc_name, isproc=False,
                              line_number=next_proc.line_number, far=next_proc.far)
        next_label.real_offset, next_label.real_seg = next_proc.real_offset, next_proc.real_seg
        next_label.used = True
        first_proc.add_label(next_proc_name, next_label)
        logging.debug("     with %s", next_proc_name)
        first_proc.merge_two_procs(new_group_name, next_proc)
        for missing_label in first_proc.provided_labels:
            self.label_to_proc[missing_label] = new_group_name
        self._context.symbols.reset_global(next_proc_name, next_label)
        self.grouped.add(next_proc_name)

    def _align_grouping_lists(self):
        changed = True
        iteration = 0
        while changed:
            iteration += 1
            logging.info(f"     Identifing proc to merge #{iteration}")
            changed = False
            for first_proc_name in self._procs:
                logging.debug("Proc %s", first_proc_name)
                first_proc = self._context.symbols.get_global(first_proc_name)
                for next_proc_name in first_proc.to_group_with:
                    if first_proc_name == next_proc_name:
                        continue

                    logging.debug("  will group with %s", next_proc_name)
                    next_proc = self._context.symbols.get_global(next_proc_name)
                    if not next_proc.to_group_with:
                        next_proc.to_group_with = set()
                    if first_proc.to_group_with == next_proc.to_group_with:
                        continue

                    first_proc.to_group_with = next_proc.to_group_with = set.union(next_proc.to_group_with,
                                                                                   first_proc.to_group_with)
                    changed = True
                logging.debug("  will group with %s", first_proc.to_group_with)

    def _leave_only_same_segment_procs(self):
        for first_proc_name in self._procs:
            logging.debug("Proc %s", first_proc_name)
            proc = self._context.symbols.get_global(first_proc_name)
            only_current_segment_procs = set()
            for other_proc_name in proc.to_group_with:
                if first_proc_name == other_proc_name \
                    or not (other_proc := self._context.symbols.get_global(other_proc_name)) \
                    or proc.segment != other_proc.segment:
                    continue
                only_current_segment_procs.add(other_proc_name)
            proc.to_group_with = only_current_segment_procs

    def _prepare_non_single_proc_data(self):
        for index, first_proc_name in enumerate(self._procs):
            first_proc = self._context.symbols.get_global(first_proc_name)

            first_proc.used_labels = self.leave_only_procs_and_labels(first_proc.used_labels)
            logging.debug("Proc %s used labels %s",  first_proc_name, first_proc.used_labels)
            logging.debug("                   provided labels %s", first_proc.provided_labels)

            missing_labels = first_proc.used_labels - first_proc.provided_labels
            logging.debug("                    missing labels %s", missing_labels)
            procs_to_merge = set()
            if not first_proc.if_terminated_proc():
                """If execution does not terminated in the procedure range when merge it with next proc"""
                if index + 1 < len(self._procs):
                    logging.info(
                        f"Execution does not terminated need to merge {first_proc_name} with {self._procs[index + 1]}")
                    procs_to_merge.add(self._procs[index + 1])
                else:
                    logging.info(f"Execution does not terminated could not find proc after {first_proc_name}")

            if missing_labels:
                procs_to_merge.add(first_proc_name)  # TODO Why?
                for missing_label in missing_labels:
                    procs_to_merge.add(
                        self.find_related_proc(missing_label))  # if label then merge proc implementing it

            if self._context.args.get("mergeprocs") == "persegment":
                self._prepare_per_segment_proc_data(first_proc_name, first_proc, procs_to_merge)

            first_proc.to_group_with = procs_to_merge
            logging.debug(" will merge %s", procs_to_merge)

    def _prepare_per_segment_proc_data(self, first_proc_name, first_proc, procs_to_merge):
        for pname in self._procs:
            if pname != first_proc_name:
                p_proc = self._context.symbols.get_global(pname)
                if first_proc.segment == p_proc.segment:
                    procs_to_merge.add(pname)

    def _link_consecutive_non_terminated_procs(self):
        last_proc_index = len(self._procs) - 1
        for index, first_proc_name in enumerate(self._procs):
            first_proc = self._context.symbols.get_global(first_proc_name)
            if first_proc.if_terminated_proc() or index >= last_proc_index:
                continue
            result = self._context.parse_text(self._procs[index + 1], start_rule="expr")
            expr = self._context.process_ast("", result)
            o = first_proc.create_instruction_object("jmp", [expr])
            o.filename = ""
            o.line_number = 0
            o.raw_line = ""
            o.syntetic = True
            first_proc.stmts.append(o)

    def generate_label_to_proc_map(self):
        for proc_name in self._procs:
            proc = self._context.symbols.get_global(proc_name)
            logging.debug("Proc %s provides: %s", proc_name, proc.provided_labels)
            for label in proc.provided_labels:
                self.label_to_proc[label] = proc_name

    def sort_procedure_list_in_linenumber_order(self, proc_list):
        """It takes a list of procedure names, and returns sorted in the order in which they appear in the program.

        :param proc_list: a list of procedure names
        :return: A list of procedure names in line number order.
        """
        # Keep all procedures even when multiple entries share the same line number.
        # Use original parse order as a stable tie-breaker to avoid set-order nondeterminism.
        original_order = {name: idx for idx, name in enumerate(self._context.proc_list)}
        return sorted(
            proc_list,
            key=lambda proc_name: (
                self._context.symbols.get_global(proc_name).line_number,
                original_order.get(proc_name, len(original_order)),
            ),
        )

    def print_how_procs_merged(self):
        """It prints out the names of the procedures that were merged together."""
        for first_proc_name in self._procs:
            first_proc = self._context.symbols.get_and_mark_global(first_proc_name)
            if not first_proc.to_group_with:
                continue
            logging.info(f"     ~{first_proc_name}")
            for p_name in first_proc.to_group_with:
                logging.info(f"       {p_name}")

    def find_related_proc(self, name):
        """:param name: the name of the global object
        :return: The name of the related proc.
        """
        from masm2c.proc import Proc
        logging.debug("get_related_proc %s", name)
        global_object = self._context.symbols.get_global(name)
        if isinstance(global_object, op.label):
            related_proc = self.label_to_proc[name]
            logging.debug(" %s is a label, related proc name: %s", name, related_proc)
        elif isinstance(global_object, Proc):
            related_proc = global_object.name
            logging.debug(" %s is a proc, related proc name: %s", name, related_proc)
        return related_proc

    def leave_only_procs_and_labels(self, all_labels):
        """It takes a list of labels and returns a list of labels that are actually labels or proc names.

        :param all_labels: a list of all labels in the program
        :return: A set of labels.
        """
        from masm2c.proc import Proc
        labels = set()  # leave only real labels
        for label_name in all_labels:
            first_label = self._context.symbols.get_global(label_name)
            if isinstance(first_label, (op.label, Proc)):
                labels.add(label_name)
        return labels

    def write_segment_file(
        self,
        segments,
        structs,
        fname,
        data_aliases=None,
        equates=None,
        abs_externs=None,
        code_symbols=None,
        defined_code_symbols=None,
        extern_code_symbols=None,
        defined_code_symbol_offsets=None,
        code_offset_aliases=None,
        module_name=None,
    ):
        jsonpickle.set_encoder_options("json", indent=2)
        with open(self.segment_sidecar_path(fname), "wb") as f:
            pickle.dump(
                (
                    segments,
                    structs,
                    data_aliases or [],
                    equates or [],
                    abs_externs or set(),
                    code_symbols or set(),
                    defined_code_symbols or set(),
                    extern_code_symbols or set(),
                    defined_code_symbol_offsets or {},
                    code_offset_aliases or [],
                    module_name,
                ),
                f,
            )

    def read_segment_files(self, asm_files):
        logging.info(" *** Merging .seg files")
        segments = OrderedDict()
        structs = OrderedDict()
        structures = structs
        data_aliases = []
        equates = []
        abs_externs = set()
        code_symbols = set()
        defined_code_symbols = set()
        extern_code_symbols = set()
        defined_code_symbol_offsets = {}
        reserved_code_symbol_offsets: set[int] = set()
        code_offset_aliases = []
        module_names: dict[str, str] = {}
        code_symbol_definers: dict[str, list[str]] = {}
        code_symbol_visible: dict[str, set[str]] = {}
        merge_args = self._context.args if isinstance(getattr(self._context, "args", None), dict) else {}
        requested_exports = {
            str(name).lower()
            for name in (
                list(merge_args.get("external_code_exports", []))
                + list(merge_args.get("public_code_exports", []))
            )
        }
        for source_file in asm_files:
            file = self.segment_sidecar_path(source_file)
            if not os.path.exists(file):
                logging.warning(f"     Skipping missing segment file {file}")
                continue
            logging.info(f"     Merging data from {file}")
            with open(file, "rb") as f:
                sidecar = pickle.load(f)
                if len(sidecar) == 2:
                    newsegments, newstructs = sidecar
                    newaliases = []
                    newequates = []
                    newabs_externs = set()
                    newcode_symbols = set()
                    newdefined_code_symbols = set()
                    newextern_code_symbols = set()
                    newdefined_code_symbol_offsets = {}
                    newcode_offset_aliases = []
                elif len(sidecar) == 3:
                    newsegments, newstructs, newaliases = sidecar
                    newequates = []
                    newabs_externs = set()
                    newcode_symbols = set()
                    newdefined_code_symbols = set()
                    newextern_code_symbols = set()
                    newdefined_code_symbol_offsets = {}
                    newcode_offset_aliases = []
                elif len(sidecar) == 4:
                    newsegments, newstructs, newaliases, newequates = sidecar
                    newabs_externs = set()
                    newcode_symbols = set()
                    newdefined_code_symbols = set()
                    newextern_code_symbols = set()
                    newdefined_code_symbol_offsets = {}
                    newcode_offset_aliases = []
                elif len(sidecar) == 5:
                    newsegments, newstructs, newaliases, newequates, newabs_externs = sidecar
                    newcode_symbols = set()
                    newdefined_code_symbols = set()
                    newextern_code_symbols = set()
                    newdefined_code_symbol_offsets = {}
                    newcode_offset_aliases = []
                elif len(sidecar) == 6:
                    newsegments, newstructs, newaliases, newequates, newabs_externs, newcode_symbols = sidecar
                    newdefined_code_symbols = set()
                    newextern_code_symbols = set()
                    newdefined_code_symbol_offsets = {}
                    newcode_offset_aliases = []
                elif len(sidecar) == 7:
                    newsegments, newstructs, newaliases, newequates, newabs_externs, newcode_symbols, newdefined_code_symbols = sidecar
                    newextern_code_symbols = set()
                    newdefined_code_symbol_offsets = {}
                    newcode_offset_aliases = []
                elif len(sidecar) == 8:
                    (
                        newsegments,
                        newstructs,
                        newaliases,
                        newequates,
                        newabs_externs,
                        newcode_symbols,
                        newdefined_code_symbols,
                        newextern_code_symbols,
                    ) = sidecar
                    newdefined_code_symbol_offsets = {}
                    newcode_offset_aliases = []
                elif len(sidecar) == 9:
                    (
                        newsegments,
                        newstructs,
                        newaliases,
                        newequates,
                        newabs_externs,
                        newcode_symbols,
                        newdefined_code_symbols,
                        newextern_code_symbols,
                        newdefined_code_symbol_offsets,
                    ) = sidecar
                    newcode_offset_aliases = []
                else:
                    (
                        newsegments,
                        newstructs,
                        newaliases,
                        newequates,
                        newabs_externs,
                        newcode_symbols,
                        newdefined_code_symbols,
                        newextern_code_symbols,
                        newdefined_code_symbol_offsets,
                        newcode_offset_aliases,
                    ) = sidecar[:10]
                if len(sidecar) > 10 and sidecar[10]:
                    module_names[str(source_file)] = str(sidecar[10])
                module_label = module_names.get(
                    str(source_file),
                    os.path.splitext(os.path.basename(str(source_file)))[0].lower(),
                )
                defined_here = {str(name).lower() for name in newdefined_code_symbols}
                for name in defined_here:
                    definers = code_symbol_definers.setdefault(name, [])
                    if module_label not in definers:
                        definers.append(module_label)
                # A defined symbol that is also extern/data/offset referenced is
                # emitted with external (weak) linkage, so same-named definitions
                # in other modules collide at link time.
                for name in newextern_code_symbols:
                    lowered = str(name).lower()
                    if lowered in defined_here:
                        code_symbol_visible.setdefault(lowered, set()).add(module_label)
                for name in defined_here & requested_exports:
                    code_symbol_visible.setdefault(name, set()).add(module_label)
                relocations = self._segment_merge_relocations(segments, newsegments)
                segments, structures = self.merge_segments(segments, structs, newsegments, newstructs)
                data_aliases.extend(self._relocate_data_aliases(newaliases, relocations))
                code_offset_aliases.extend(self._relocate_data_aliases(newcode_offset_aliases, relocations))
                code_symbol_merge_offset = self._code_symbol_merge_offset(newsegments, relocations)
                equates.extend(self._relocate_equates(newequates, relocations, newsegments))
                abs_externs.update(str(name).lower() for name in newabs_externs)
                code_symbols.update(str(name).lower() for name in newcode_symbols)
                defined_code_symbols.update(str(name).lower() for name in newdefined_code_symbols)
                extern_code_symbols.update(str(name).lower() for name in newextern_code_symbols)
                reserved_code_symbol_offsets.update(int(offset) for offset in newdefined_code_symbol_offsets.values())
                defined_code_symbol_offsets.update(
                    (str(name).lower(), self._relocate_code_symbol_offset(offset, code_symbol_merge_offset))
                    for name, offset in newdefined_code_symbol_offsets.items()
                )
        if self.merge_data_segments:
            self._layout_public_segment_class_storage(segments)
        self._context.data_aliases = self._deduplicate_data_alias_names(data_aliases)
        relocated_alias_offsets = {
            str(alias.name).lower(): int(alias.offset)
            for alias in code_offset_aliases
            if getattr(alias, "name", "")
        }
        code_offset_alias_names = set(relocated_alias_offsets)
        relocated_alias_offsets.update(
            self._data_label_code_offsets(self._context.data_aliases, segments, defined_code_symbol_offsets)
        )
        storage_reserved_names = self._merged_symbol_names(segments, structures, self._context.data_aliases)
        reserved_names = set(storage_reserved_names)
        reserved_names.update(code_symbols)
        self._context.exported_equates = self._deduplicate_equates(
            equates,
            abs_externs,
            reserved_names,
            defined_code_symbols,
            extern_code_symbols,
        )
        requested_public_code_offsets = {
            str(name).lower()
            for name in (
                self._context.args.get("public_code_exports", [])
                if isinstance(getattr(self._context, "args", None), dict)
                else []
            )
        }
        exported_code_symbols = extern_code_symbols | requested_public_code_offsets
        (
            self._context.exported_code_symbol_offsets,
            self._context.exported_callable_code_symbol_offsets,
        ) = self._assign_aggregate_code_offsets(
            defined_code_symbol_offsets,
            defined_code_symbols,
            exported_code_symbols,
            relocated_alias_offsets,
            code_offset_alias_names,
            storage_reserved_names,
            reserved_code_symbol_offsets,
        )
        self._assign_qualified_colliding_code_offsets(
            code_symbol_definers,
            code_symbol_visible,
            reserved_code_symbol_offsets,
        )
        self._context.all_defined_code_symbol_offsets = {
            str(name).lower(): int(offset)
            for name, offset in defined_code_symbol_offsets.items()
        }
        self._context.merged_module_names = module_names
        return segments, structures

    def _assign_qualified_colliding_code_offsets(
        self,
        code_symbol_definers: dict[str, list[str]],
        code_symbol_visible: dict[str, set[str]],
        reserved_code_symbol_offsets: set[int],
    ) -> None:
        """Disambiguate same-named code symbols defined by several modules.

        A real MASM link keeps non-PUBLIC symbols module-local, but the
        generated code emits externally visible (weak) wrappers for any
        code symbol referenced by data tables or OFFSET, so duplicates from
        different modules silently bind to whichever object the linker picks
        first (e.g. a FAR ``InitCtrlDevice`` chain landing in a NEAR sibling,
        corrupting the emulated stack on return).

        For every name that is link-visible in two or more modules, the
        earlier definers get module-qualified ``name__<module>`` functions and
        ``kglobal_name__<module>`` dispatch handles; the last link-visible
        definer keeps the canonical function name so plain extern calls still
        bind.  The renames are emitted as compile-time ``#define``s at the end
        of ``_equates.h`` (after all constant definitions, so the kglobal_*
        macros only affect use sites).
        """
        exported_offsets = getattr(self._context, "exported_code_symbol_offsets", None)
        callable_offsets = getattr(self._context, "exported_callable_code_symbol_offsets", None)
        self._context.code_label_renames = []
        if not exported_offsets or not code_symbol_definers:
            return
        if callable_offsets is None:
            callable_offsets = exported_offsets
        used_offsets = {int(v) for v in exported_offsets.values()}
        used_offsets.update(int(v) for v in callable_offsets.values())
        used_offsets.update(int(v) for v in reserved_code_symbol_offsets)
        next_offset = max(used_offsets, default=0x1000) + 1
        renames: list[tuple[str, str, str]] = []
        for name in sorted(code_symbol_definers):
            definers = code_symbol_definers[name]
            if len(definers) < 2 or name not in exported_offsets:
                continue
            visible = [m for m in definers if m in code_symbol_visible.get(name, set())]
            if len(visible) < 2:
                # Other definers are module-local (static) and never collide.
                continue
            keeper = visible[-1]
            keeper_handle = int(exported_offsets[name])
            for module in visible:
                qualified = f"{name}__{re.sub(r'[^A-Za-z0-9_]', '_', str(module).lower())}"
                module_macro = f"M2C_MODULE_{re.sub(r'[^A-Za-z0-9_]', '_', str(module).upper()) or 'UNKNOWN'}"
                if module != keeper:
                    while next_offset in used_offsets:
                        next_offset += 1
                    exported_offsets[qualified] = next_offset
                    callable_offsets[qualified] = next_offset
                    used_offsets.add(next_offset)
                    next_offset += 1
                    renames.append((module_macro, name, qualified))
                else:
                    # The keeper's dispatch handle is also qualified so that its
                    # own tables store a distinct value; no bare kglobal_<name>
                    # constant is emitted for colliding names.
                    exported_offsets[qualified] = keeper_handle
                renames.append((module_macro, f"kglobal_{name}", f"kglobal_{qualified}"))
        self._context.code_label_renames = renames

    @staticmethod
    def _data_label_code_offsets(data_aliases, segments: OrderedDict, defined_code_symbol_offsets: dict[str, int]):
        """Return aggregate code-relative offsets for exported data labels."""
        offsets: dict[str, int] = {}
        defined = {str(name).lower() for name in defined_code_symbol_offsets}
        segments_by_name = {str(name).lower(): segment for name, segment in segments.items()}
        for alias in data_aliases:
            name = str(getattr(alias, "name", "")).lower()
            if not name or name not in defined:
                continue
            segment_name = str(getattr(alias, "segment", "")).lower()
            segment = segments_by_name.get(segment_name)
            if segment is None:
                continue
            offsets[name] = int(getattr(segment, "offset", 0)) + int(getattr(alias, "offset", 0))
        return offsets

    @staticmethod
    def _relocate_equates(equates, relocations: dict[str, tuple[str, int]], segments: OrderedDict):
        """Relocate captured code-segment `$` equates from module to aggregate offsets."""
        relocated = []
        for item in equates:
            if len(item) < 5:
                relocated.append(item)
                continue
            name, value, public, segment, location_counter_equate = item[:5]
            segment_name = str(segment).lower()
            segment_info = segments.get(segment_name)
            merge_offset = int(relocations.get(segment_name, (segment_name, 0))[1])
            if location_counter_equate and merge_offset and segment_info and Gen._is_code_storage_segment(segment_info):
                value = Gen._relocate_location_counter_equate_value(str(value), merge_offset)
            relocated.append((name, value, public))
        return relocated

    @staticmethod
    def _relocate_location_counter_equate_value(value: str, merge_offset: int) -> str:
        """Relocate simple captured-offset equate values emitted by the parser."""
        term = r"(?:0x[0-9a-fA-F]+|\d+)"

        def parse_int(raw: str) -> int:
            return int(raw, 16) if raw.lower().startswith("0x") else int(raw)

        def render_int(raw: str) -> str:
            return str(parse_int(raw) + merge_offset)

        if re.fullmatch(term, value):
            return render_int(value)
        match = re.fullmatch(rf"({term})\s*-\s*({term})", value)
        if match:
            left, right = match.groups()
            return f"{render_int(left)}-{render_int(right)}"
        return value

    @staticmethod
    def _assign_aggregate_code_offsets(
        defined_code_symbol_offsets: dict[str, int],
        defined_code_symbols: set[str],
        exported_code_symbols: set[str],
        relocated_alias_offsets: dict[str, int],
        code_offset_alias_names: set[str],
        reserved_names: set[str],
        reserved_code_symbol_offsets: set[int] | None = None,
    ) -> tuple[dict[str, int], dict[str, int]]:
        """Assign unique aggregate dispatch handles for exported code symbols."""
        exported_offsets: dict[str, int] = {}
        callable_offsets: dict[str, int] = {}
        reserved_offsets = {int(offset) for offset in defined_code_symbol_offsets.values()}
        reserved_offsets.update(int(offset) for offset in reserved_code_symbol_offsets or set())
        reserved_offsets.update(int(offset) for offset in relocated_alias_offsets.values())
        used_offsets: set[int] = set()
        next_offset = 0x1000

        for name in defined_code_symbol_offsets:
            if name not in exported_code_symbols:
                continue
            if name in reserved_names:
                exported_offsets[name] = relocated_alias_offsets.get(name, defined_code_symbol_offsets[name])
                continue
            if name not in defined_code_symbols:
                exported_offsets[name] = relocated_alias_offsets.get(name, defined_code_symbol_offsets[name])
                continue
            if name in code_offset_alias_names:
                exported_offsets[name] = relocated_alias_offsets[name]
                continue
            while next_offset in reserved_offsets or next_offset in used_offsets:
                next_offset += 1
            exported_offsets[name] = next_offset
            callable_offsets[name] = next_offset
            used_offsets.add(next_offset)
            next_offset += 1

        return exported_offsets, callable_offsets

    @staticmethod
    def _unique_code_symbol_offsets(offsets):
        result = OrderedDict()
        used_offsets = set()
        for name, offset in sorted(offsets.items()):
            normalized = str(name).lower()
            if normalized == "main":
                continue
            if offset in used_offsets:
                continue
            result[normalized] = offset
            used_offsets.add(offset)
        return result

    @staticmethod
    def _deduplicate_equates(
        equates,
        abs_externs=None,
        reserved_names=None,
        defined_code_symbols=None,
        extern_code_symbols=None,
    ):
        abs_externs = abs_externs or set()
        reserved_names = reserved_names or set()
        defined_code_symbols = defined_code_symbols or set()
        extern_code_symbols = extern_code_symbols or set()
        result = OrderedDict()
        for item in equates:
            if len(item) == 2:
                name, value = item
                public = True
            elif len(item) == 3:
                name, value, public = item
            else:
                name, value, public = item[:3]
            normalized_name = str(name).lower()
            is_code_symbol_equate = (
                public
                and normalized_name in extern_code_symbols
                and normalized_name not in defined_code_symbols
            )
            if normalized_name in reserved_names and not is_code_symbol_equate:
                continue
            if Gen._is_host_reserved_equate_name(normalized_name):
                continue
            if Gen._is_module_local_equate_value(str(value)):
                continue
            if Gen._is_non_numeric_bare_equate_value(str(value)):
                continue
            if not public and normalized_name not in abs_externs:
                continue
            result[str(name)] = (str(value), is_code_symbol_equate)
        return [(name, value, is_code_symbol) for name, (value, is_code_symbol) in result.items()]

    @staticmethod
    def _is_host_reserved_equate_name(name: str) -> bool:
        return name.startswith("_") or name in {
            "bits",
            "num",
            "quo",
            "rem",
            "string",
            "val",
        }

    @staticmethod
    def _is_module_local_equate_value(value: str) -> bool:
        if "$" in value or "&" in value or "m2c::" in value:
            return True
        # Unary dereference "*(" only counts at expression start or after an
        # operator/opening paren; "2*(expr)" is plain multiplication.
        return bool(re.search(r"(?:^|[\s(+\-*/%<>=&|^!~])\*\s*\(", value))

    @staticmethod
    def _is_non_numeric_bare_equate_value(value: str) -> bool:
        return bool(re.fullmatch(r"[A-Za-z_@$?][A-Za-z0-9_@$?]*", value.strip()))

    @staticmethod
    def _merged_symbol_names(segments, structures, data_aliases) -> set[str]:
        names = {str(name).lower() for name in structures.keys()}
        names.update(str(name).lower() for name in segments.keys())
        for segment in segments.values():
            for data in segment.getdata():
                label = getattr(data, "label", "")
                if label:
                    names.add(str(label).lower())
        for alias in data_aliases:
            name = getattr(alias, "name", "")
            if name:
                names.add(str(name).lower())
        names.update({
            "npos",
        })
        return names

    @staticmethod
    def _deduplicate_data_alias_names(data_aliases):
        seen: set[str] = set()
        for alias in data_aliases:
            name = alias.name.lower()
            if name not in seen:
                seen.add(name)
                continue
            source = os.path.splitext(os.path.basename(getattr(alias, "filename", "") or ""))[0].lower()
            suffix_parts = [part for part in (source, alias.segment, f"{alias.offset:x}") if part]
            suffix = "_".join(re.sub(r"[^A-Za-z0-9_]", "_", part) for part in suffix_parts) or "dup"
            candidate = f"{name}__{suffix}"
            index = 2
            while candidate.lower() in seen:
                candidate = f"{name}__{suffix}_{index}"
                index += 1
            alias.name = candidate
            seen.add(candidate.lower())
        return data_aliases

    @staticmethod
    def segment_sidecar_path(source_path: str) -> str:
        root, ext = os.path.splitext(source_path)
        if ext.lower() in {".asm", ".lst"}:
            return f"{root}.seg"
        if ext.lower() == ".seg":
            return source_path
        return f"{source_path}.seg"

    def merge_segments(self, allsegments: OrderedDict, allstructs: OrderedDict, newsegments: OrderedDict,
                       newstructs: OrderedDict):
        """If the segment is public and the user wants to merge public segments, then merge the segment. Otherwise, if the
        segment already exists, overwrite it.

        :param allsegments: OrderedDict
        :param allstructs: OrderedDict
        :param newsegments: OrderedDict
        :param newstructs: OrderedDict
        :return: Merged segments and merged structs
        """
        if self.merge_data_segments:
            logging.info("Will merge public data segments")
        for segment_name, segment_value in newsegments.items():
            segclass = segment_value.segclass
            ispublic = segment_value.options and "public" in segment_value.options
            if (
                segclass
                and ispublic
                and self.merge_data_segments
                and self._is_code_storage_segment(segment_value)
            ):
                if segclass not in allsegments:
                    allsegments[segclass] = segment_value
                    self._segment_aliases(allsegments[segclass]).setdefault(segment_value.name, 0)
                else:
                    merge_offset = self._segment_extent(allsegments[segclass])
                    self._segment_aliases(allsegments[segclass]).setdefault(segment_value.name, merge_offset)
                    data = segment_value.getdata()
                    for d in data:
                        self._relocate_data_record(d, merge_offset)
                        allsegments[segclass].append(d)
            elif self.merge_data_segments and segment_name in allsegments and (
                segment_value.getsize() > 0 or allsegments[segment_name].getsize() > 0
            ):
                self._check_for_segment_overwrite(allsegments, segment_name, segment_value)
                merge_offset = self._segment_extent(allsegments[segment_name])
                for data in segment_value.getdata():
                    self._relocate_data_record(data, merge_offset)
                    allsegments[segment_name].append(data)
            else:
                self._check_for_segment_overwrite(allsegments, segment_name, segment_value)
                allsegments[segment_name] = segment_value

        self._check_for_struct_overwrite(allstructs, newstructs)
        allstructs.update(newstructs)
        return allsegments, allstructs

    def _segment_merge_relocations(self, allsegments: OrderedDict, newsegments: OrderedDict) -> dict[str, tuple[str, int]]:
        relocations: dict[str, tuple[str, int]] = {}
        for segment_name, segment_value in newsegments.items():
            segclass = segment_value.segclass
            ispublic = segment_value.options and "public" in segment_value.options
            if (
                segclass
                and ispublic
                and self.merge_data_segments
                and self._is_code_storage_segment(segment_value)
            ):
                merge_offset = self._segment_extent(allsegments[segclass]) if segclass in allsegments else 0
                relocations[segment_name] = (segclass, merge_offset)
            elif self.merge_data_segments and segment_name in allsegments and (
                segment_value.getsize() > 0 or allsegments[segment_name].getsize() > 0
            ):
                relocations[segment_name] = (segment_name, self._segment_extent(allsegments[segment_name]))
            else:
                relocations[segment_name] = (segment_name, 0)
        return relocations

    @staticmethod
    def _segment_extent(segment) -> int:
        return max(
            [segment.getsize(), *(data.offset + data.getsize() for data in segment.getdata())],
            default=0,
        )

    @classmethod
    def _code_symbol_merge_offset(
        cls,
        segments: OrderedDict,
        relocations: dict[str, tuple[str, int]],
    ) -> int:
        """Return the public code-segment relocation for a module sidecar."""
        for segment_name, segment in segments.items():
            if cls._is_code_storage_segment(segment):
                return int(relocations.get(segment_name, (segment_name, 0))[1])
        return 0

    @staticmethod
    def _relocate_code_symbol_offset(offset: int, merge_offset: int) -> int:
        """Relocate near code offsets while leaving far/listing addresses intact."""
        offset = int(offset)
        if not merge_offset or offset > 0xFFFF:
            return offset
        return offset + int(merge_offset)

    @classmethod
    def _layout_public_segment_class_storage(cls, segments: OrderedDict) -> None:
        occupied: list[tuple[int, int]] = []
        for segment in segments.values():
            if not cls._is_code_storage_segment(segment):
                continue
            extent = cls._segment_extent(segment)
            if extent:
                occupied.append((int(segment.offset), int(segment.offset) + extent))

        next_free = cls._align_storage_offset(max((end for _start, end in occupied), default=0))
        for segment in segments.values():
            if cls._is_code_storage_segment(segment) or not cls._is_public_segment_class(segment):
                continue
            extent = cls._segment_extent(segment)
            if not extent:
                continue
            start = int(segment.offset)
            end = start + extent
            if any(cls._intervals_overlap(start, end, used_start, used_end) for used_start, used_end in occupied):
                start = next_free
                end = start + extent
                segment.offset = start
                segment.linked_storage_offset_authoritative = True
            occupied.append((start, end))
            next_free = cls._align_storage_offset(max(next_free, end))

    @staticmethod
    def _is_public_segment_class(segment) -> bool:
        return bool(getattr(segment, "segclass", None) and getattr(segment, "options", None) and "public" in segment.options)

    @classmethod
    def _is_code_storage_segment(cls, segment) -> bool:
        if not cls._is_public_segment_class(segment):
            return False
        name = str(getattr(segment, "name", "")).lower()
        segclass = str(getattr(segment, "segclass", "")).lower()
        return "code" in name or "code" in segclass or name in {"cseg", "codesg"} or segclass in {"cseg", "codesg"}

    @staticmethod
    def _intervals_overlap(start: int, end: int, used_start: int, used_end: int) -> bool:
        return start < used_end and used_start < end

    @staticmethod
    def _align_storage_offset(offset: int) -> int:
        return (offset + 0x0f) & ~0x0f

    @staticmethod
    def _relocate_data_record(data, merge_offset: int) -> None:
        if merge_offset:
            data.offset += merge_offset

    @staticmethod
    def _relocate_data_aliases(aliases, relocations: dict[str, tuple[str, int]]):
        for alias in aliases:
            canonical_segment, merge_offset = relocations.get(alias.segment, (alias.segment, 0))
            alias.segment = canonical_segment
            alias.offset += merge_offset
        return aliases

    @staticmethod
    def _segment_aliases(segment):
        if not hasattr(segment, "segment_aliases"):
            segment.segment_aliases = {segment.name: 0}
        return segment.segment_aliases

    def _check_for_segment_overwrite(self, allsegments, segment_name, segment_value):
        if segment_name in allsegments and (segment_value.getsize() > 0 or allsegments[segment_name].getsize() > 0):
            old = jsonpickle.encode(allsegments[segment_name], unpicklable=False)
            new = jsonpickle.encode(segment_value, unpicklable=False)
            if old != new and segment_name not in self._warned_segment_overwrites:
                logging.warning(
                    "Overwriting segment %s during merge (old size 0x%x -> new size 0x%x)",
                    segment_name,
                    allsegments[segment_name].getsize(),
                    segment_value.getsize(),
                )
                self._warned_segment_overwrites.add(segment_name)

    def _check_for_struct_overwrite(self, allstructs: dict, newstructs: dict):
        if allstructs != newstructs and set(allstructs.keys()) & set(newstructs.keys()):
            for struct_name, struct_value in newstructs.items():
                if struct_name not in allstructs:
                    continue
                old = jsonpickle.encode(allstructs[struct_name], unpicklable=False)
                new = jsonpickle.encode(struct_value, unpicklable=False)
                if old != new and struct_name not in self._warned_struct_overwrites:
                    logging.warning("Overwriting structure %s during merge", struct_name)
                    self._warned_struct_overwrites.add(struct_name)

    def _render_procedure(self, name, def_skip=0):
        """It takes a procedure name, and returns a C++ string containing for that procedure.

        :param name: The name of the procedure to be rendered
        :param def_skip: defaults to 0 (optional)
        :return: The body of the procedure and the segment it is in.
        """
        logging.info("     Generating proc %s", name)
        try:
            skip = def_skip
            self.__pushpop_count = 0
            self.temps_max = 0
            if g := self._context.symbols.get_global(name):
                self.proc = g
            else:
                logging.debug("No procedure named %s, trying label", name)
                off, src_proc, skip = self._context.get_offset(name)

                from masm2c.proc import Proc
                self.proc = Proc(name)
                self.proc.stmts = copy(src_proc.stmts)
                self.proc.provided_labels = copy(src_proc.provided_labels)

            self._proc_addr.append((name, self.proc.offset))
            self.body = ""

            entry_point = ""
            if g := self._context.symbols.get_global(self._context.entry_point) and isinstance(g, op.label) and self.label_to_proc[g.name] == self.proc:
                entry_point = self._context.entry_point
            self.body += self.proc_strategy.function_header(name, entry_point)

            self.proc.visit(self, skip)
            self.body = re.sub(
                r"(__dispatch_call,\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*[+-]\s*\d+)",
                r"\1m2c::k\2\3",
                self.body,
            )

            labels = set(self.proc.provided_labels)
            labels.update(label for label, proc_name in self.label_to_proc.items() if proc_name == name)
            labels.update(label for label, proc_name in self.groups.items() if proc_name == name)

            offsets = self.make_enums_and_labels(labels)
            self.body += self.produce_jump_table(offsets)

            segment = self.proc.segment
            self.proc = None

            if self.__pushpop_count != 0:
                logging.warning("push/pop balance = %d non zero at the exit of proc", self.__pushpop_count)
            return self.body, segment
        except (CrossJump, op.Unsupported) as e:
            logging.exception("%s: ERROR: %s", name, e)
            self.__failed.append(name)
            raise
        except Exception as ex:
            logging.exception(f"Exception {ex.args} for {name}")
            raise

    def produce_jump_table(self, offsets):
        raise NotImplementedError()

    @staticmethod
    def isrelativejump(label: Expression) -> bool:
        return (
            isinstance(label, lark.Tree)
            and isinstance(label.children[0], lark.Tree)
            and label.children[0].data == "adddir"
            and isinstance(label.children[0].children[0], lark.Tree)
            and label.children[0].children[0].data == "ptrdir3"
            and isinstance(label.children[0].children[0].children[0], lark.Token)
            and label.children[0].children[0].children[0].type == "LABEL"
            and label.children[0].children[0].children[0].value == "dol"
        ) or (
            isinstance(label, lark.Tree)
            and isinstance(label.children[0], lark.Tree)
            and label.children[0].data == "adddir"
            and isinstance(label.children[0].children[0], lark.Tree)
            and label.children[0].children[0].data == "dollar"
        )

    def dump_globals(self) -> None:
        """Dumps the global variables to a file."""
        from masm2c.proc import Proc
        name = f"{self._namespace.lower()}.list"
        logging.info(f" *** Generating globals listing {name}")

        jsonpickle.set_encoder_options("json", indent=2)
        with open(name, "w") as lst:
            lst.write("Segment:\n")
            for segment_name in self._context.segments:
                lst.write(f"{segment_name}\n")

            lst.write("\nLabels:\n")
            for global_obj in self._context.symbols.get_globals().values():
                if isinstance(global_obj, op.label):
                    lst.write(f"{global_obj.name}\n")

            lst.write("\nProcs:\n")
            for global_obj in self._context.symbols.get_globals().values():
                if isinstance(global_obj, Proc):
                    lst.write(f"{global_obj.name} {global_obj.offset}\n")

            lst.write("\nVars:\n")
            for global_obj in self._context.symbols.get_globals().values():
                if isinstance(global_obj, op.var):
                    lst.write(f"{global_obj.name} {global_obj.offset}\n")

            lst.write(
                jsonpickle.encode(
                    (self._context.symbols.get_globals(), self._context.segments, self._context.structures),
                    max_depth=8,
                )
            )


    def make_enums_and_labels(self, labels):
        offsets = []
        for k in labels:
            k = re.sub(r"\W", "_", k)
            offsets.append((k.lower(), self.mangle_label(k)))
        return sorted(offsets, key=lambda t: t[1])

    def mangle_label(self, name: str) -> str:
        raise NotImplementedError()

    def convert_asm_number_into_c(self, expr: str, radix: int=10) -> str:
        """It tryes to convert assembler number in any base to a C number string with the same base.

        :param result: The expression to convert
        :param radix: The radix of the number, defaults to 10 (optional)
        :return: The number in the specified radix.
        """
        try:
            from masm2c.parser import parse_asm_number
            radix, sign, value = parse_asm_number(expr, radix)

            result = self.produce_number(expr, radix, sign, value)
        except Exception as ex:
            logging.exception("Failed to parse number %s radix %d %s", expr, radix, ex)
            result = expr

        return result

    def produce_number(self, expr: str, radix: int, sign: str, value: str) -> str:
        raise NotImplementedError()


def guess_int_size(v: int) -> int:
    """It returns the number of bytes needed to store the given integer.

    :param v: integer
    :return: The size of the integer.
    """
    size = 0
    if v < 0:
        v = -2 * v - 1
    if v < 2**8:
        size = 1
    elif v < 2**16:
        size = 2
    elif v < 2**32:
        size = 4
    else:
        logging.error("too big number %d", v)

    logging.debug("guess_int_size %d", size)
    return size


CPP_KEYWORDS = {
    "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor", "bool",
    "break", "case", "catch", "char", "char16_t", "char32_t", "class", "compl", "concept",
    "const", "consteval", "constexpr", "constinit", "const_cast", "continue", "co_await",
    "co_return", "co_yield", "decltype", "default", "delete", "do", "double", "dynamic_cast",
    "else", "enum", "explicit", "export", "extern", "false", "float", "for", "friend",
    "goto", "if", "inline", "int", "long", "mutable", "namespace", "new", "noexcept",
    "not", "not_eq", "nullptr", "operator", "or", "or_eq", "private", "protected",
    "public", "register", "reinterpret_cast", "requires", "return", "short", "signed",
    "sizeof", "static", "static_assert", "static_cast", "struct", "switch", "template",
    "this", "thread_local", "throw", "true", "try", "typedef", "typeid", "typename",
    "union", "unsigned", "using", "virtual", "void", "volatile", "wchar_t", "while",
    "xor", "xor_eq",
    "alarm", "tan",
}


def avoid_cpp_keyword(name: str) -> str:
    return f"asm_{name}" if name.lower() in CPP_KEYWORDS else name


def mangle_asm_labels(name: str) -> str:
    """Modifies assembler functions to be acceptable for other languages.

    :param name: the name of assembler the function
    :return: The name of the C function.
    """
    if name.lower() == "main":
        name = "asmmain"
    name = name.replace("$", "_tmp").replace("?", "que")
    return avoid_cpp_keyword(name)


class SkipCode(Exception):
    pass


class CrossJump(Exception):
    pass


class InjectCode(Exception):
    """A way to inject additional instructions during processing of some instruction."""

    def __init__(self, cmd) -> None:
        self.cmd = cmd
