endOfLine
  : /[\r\n]+/
  ;
dotcomma
  : endOfLine | comment
  ; 
eqDir
  : id  "=" immExpr dotcomma
  ; 
addOp
  : "+" | "-"
  ; 
aExpr
  : term | aExpr  "&&" term
  ; 
altId
  : id
  ; 
arbitraryText
  : charList
  ; 
asmInstruction
  : mnemonic  exprList? 
  ; 
assumeDir
  : "ASSUME" assumeList dotcomma| "ASSUME NOTHING" dotcomma
  ; 
assumeList 
  : assumeRegister| assumeList  "," assumeRegister
  ; 
assumeReg
  : register ":" assumeVal
  ; 
assumeRegister
  : assumeSegReg| assumeReg
  ; 
assumeSegReg
  : segmentRegister ":" assumeSegVal
  ; 
assumeSegVal
  : frameExpr| "NOTHING" | "ERROR" 
  ; 
assumeVal
  : qualifiedType| "NOTHING" | "ERROR" 
  ; 
bcdConst
  :  sign?  decNumber
  ; 
binaryOp
  : "=="| "!="| ">="| "<="| ">"| "<"| "&" 
  ; 
eqconstExpr
  : "=" constExpr
  ;
bitDef
  : bitFieldId ":" bitFieldSize eqconstExpr?
  ; 
bitDefList
  : bitDef| bitDefList  "," dotcomma?  bitDef
  ; 
bitFieldId 
  : id 
  ; 
bitFieldSize
  : constExpr
  ; 
ifcexpr
  : ".IF" cExpr
  ;
blockStatements
  : directiveList| ".CONTINUE" ifcexpr? | ".BREAK" ifcexpr?
  ; 
bool
  : "TRUE" | "FALSE" 
  ; 
byteRegister
  : 'AL' | 'AH' | 'BL' | 'BH' | 'CL' | 'CH' | 'DL' | 'DH' 
  ; 
cExpr
  : aExpr| cExpr ":" aExpr
  ; 
character
  : /[^\n]/
  ; 
charList
  : character| charList character
  ; 
className
  : string
  ; 
commDecl
  :  nearfar?   langType?  id ":" commType eqconstExpr?
  ; 
commDir
  : "COMM" commList dotcomma
  ; 
comment
  : ";" text dotcomma
  ; 
commentDir
  : "COMMENT" delimiter text text delimiter text dotcomma
  ; 
commList
  : commDecl| commList  "," commDecl
  ; 
commType
  : type| constExpr
  ; 
constant
  : digits  radixOverride? 
  ; 
constExpr
  : expr
  ; 
contextDir
  : "PUSHCONTEXT" contextItemList dotcomma| "POPCONTEXT" contextItemList dotcomma
  ; 
contextItem
  : "ASSUMES" | "RADIX" | "LISTING" | "CPU" | "ALL" 
  ; 
contextItemList
  : contextItem| contextItemList  "," contextItem
  ; 
controlBlock
  : whileBlock| repeatBlock
  ; 
controlDir
  : controlIf| controlBlock
  ; 
controlElseif
  : ".ELSEIF" cExpr dotcomma directiveList controlElseif? 
  ; 

elsedirectiveList
  : ".ELSE" dotcomma directiveList
  ;
controlIf
  : ".IF" cExpr dotcomma directiveList controlElseif? elsedirectiveList? ".ENDIF" dotcomma
  ; 
coprocessor
  : ".8087" | ".287" | ".387" | ".NO87" 
  ; 
crefDir
  : crefOption dotcomma
  ; 
crefOption
  : ".CREF" | ".XCREF" idList? | ".NOCREF" idList? 
  ; 
cxzExpr
  : expr| "!" expr| expr  "==" expr| expr  "!=" expr
  ; 
dataDecl
  : "DB" | "DW" | "DD" | "DF" | "DQ" | "DT" | dataType | typeId
  ; 
dataDir
  :  id?  dataItem dotcomma
  ; 
dataItem
  : dataDecl scalarInstList| structTag structInstList| typeId structInstList| unionTag structInstList| recordTag recordInstList
  ; 
dataType
  : "BYTE" | "SBYTE" | "WORD" | "SWORD" | "DWORD" | "SDWORD" | "FWORD" | "QWORD" | "TBYTE" | "REAL4" | "REAL8" | "REAL10" 
  ; 
decdigit
  : /\d/
  ; 
decNumber
  : decdigit| decNumber decdigit
  ; 
delimiter
  : /[^\b\t\v\f\r\x1a\s]/
  ; 
digits
  : decdigit| digits decdigit| digits hexdigit
  ; 
directive
  : generalDir| segmentDef
  ; 
directiveList
  : directive| directiveList directive
  ; 
distance
  : nearfar| "NEAR16" | "NEAR32" | "FAR16" | "FAR32" 
  ; 
e01
  : e01 orOp e02| e02
  ; 
e02
  : e02 "AND" e03| e03
  ; 
e03
  : "NOT" e04| e04
  ; 
e04
  : e04 relOp e05| e05
  ; 
e05
  : e05 addOp e06| e06
  ; 
e06
  : e06 mulOp e07| e06 shiftOp e07| e07
  ; 
e07
  : e07 addOp e08| e08
  ; 
e08
  : "HIGH" e09| "LOW" e09| "HIGHWORD" e09| "LOWWORD" e09| e09
  ; 
e09
  : "OFFSET" e10| "SEG" e10| "LROFFSET" e10| "TYPE" e10| "THIS" e10| e09 "PTR" e10| e09 ":" e10| e10
  ; 
e10
  : e10 "." e11| e10  expr? | e11
  ; 
e11
  : "(" expr ")"|  expr? | "WIDTH" id| "MASK" id| "SIZE" sizeArg| "SIZEOF" sizeArg| "LENGTH" id| "LENGTHOF" id | recordConst| string| constant| type| id| "$"| segmentRegister| register| "ST" | "ST" "(" expr ")"
  ; 
echoDir
  : "ECHO" arbitraryText dotcomma "%OUT" arbitraryText dotcomma
  ; 
elseifBlock
  : elseifStatement dotcomma directiveList elseifBlock? 
  ; 
elseifStatement
  : "ELSEIF" constExpr| "ELSEIFE" constExpr| "ELSEIFB" textItem| "ELSEIFNB" textItem | "ELSEIFDEF" id| "ELSEIFNDEF" id| "ELSEIFDIF" textItem "," textItem| "ELSEIFDIFI" textItem "," textItem| "ELSEIFIDN" textItem "," textItem| "ELSEIFIDNI" textItem "," textItem| "ELSEIF1" | "ELSEIF2" 
  ; 
endDir
  : "END" immExpr?  dotcomma
  ; 
endpDir
  : procId "ENDP" dotcomma
  ; 
endsDir
  : id "ENDS" dotcomma
  ; 
equDir
  : textMacroId "EQU" equType dotcomma
  ; 
equType
  : immExpr| textLiteral
  ; 
errorDir
  : errorOpt dotcomma
  ; 
errorOpt
  : ".ERR" textItem? | ".ERRE" constExpr optText? | ".ERRNZ" constExpr optText? | ".ERRB" textItem optText? | ".ERRNB" textItem optText? | ".ERRDEF" id  optText? | ".ERRNDEF" id optText? | ".ERRDIF" textItem "," textItem  optText? | ".ERRDIFI" textItem "," textItem  optText? | ".ERRIDN" textItem "," textItem  optText? | ".ERRIDNI" textItem "," textItem  optText? | ".ERR1" textItem? | ".ERR2" textItem?  
  ; 
exitDir
  : ".EXIT" expr?  dotcomma
  ; 
exitmDir
  : "EXITM" | "EXITM" textItem
  ; 
exponent
  : "E"  sign?  decNumber
  ; 
expr
  : "SHORT" e05| ".TYPE" e01| "OPATTR" e01| e01
  ; 
exprList
  : expr| exprList  ","  expr
  ; 
altId
  : "(" altId ")"
  ;
externDef
  :  langType?  id altId? ":" externType
  ; 
externDir
  : externKey externList dotcomma
  ; 
externKey
  : "EXTRN" | "EXTERN" | "EXTERNDEF" 
  ; 
externList
  : externDef| externList  "," dotcomma?  externDef
  ; 
externType
  : "ABS" | qualifiedType
  ; 
fieldAlign
  : constExpr
  ; 
fieldInit
  :  initValue? | structInstance
  ; 
fieldInitList
  : fieldInit| fieldInitList ","  dotcomma?  fieldInit
  ; 
fileChar
  : delimiter
  ; 
fileCharList
  : fileChar| fileCharList fileChar
  ; 
fileSpec
  : fileCharList| textLiteral
  ; 
flagName
  : "ZERO? "| "CARRY?" | "OVERFLOW?"|"SIGN?"| "PARITY?"
  ; 
floatNumber 
  :  sign?  decNumber "." decNumber?   exponent? | digits "R"| digits "r"
  ; 
forcDir
  : "FORC" | "IRPC" 
  ; 
forDir
  : "FOR" | "IRP" 
  ; 
dotdotforParmType
  : ":" forParmType
  ;
forParm
  : id dotdotforParmType?
  ; 
forParmType
  : "REQ" | "=" textLiteral
  ; 
frameExpr
  : "SEG" id | "DGROUP" ":" id| segmentRegister ":" id| id
  ; 
generalDir
  : modelDir | segOrderDir | nameDir| includeLibDir | commentDir| groupDir | assumeDir| structDir | recordDir | typedefDir| externDir | publicDir | commDir | protoTypeDir| equDir | eqDir | textDir| contextDir | optionDir | processorDir| radixDir | titleDir | pageDir | listDir | crefDir | echoDir| ifDir | errorDir | includeDir | macroDir | macroCall | macroRepeat | purgeDir| macroWhile | macroFor | macroForc| aliasDir
  ; 
aliasDir
  : "ALIAS"
  ;
gpRegister
  : 'AX' | 'EAX' | 'BX' | 'EBX' | 'CX' | 'ECX' | 'DX' | 'EDX'| 'BP' | 'EBP' | 'SP' | 'ESP' | 'DI' | 'EDI' | 'SI' | 'ESI'
  ; 
groupDir 
  : groupId "GROUP" segIdList
  ; 
groupId
  : id
  ; 
hexdigit
  : /[A-Fa-f]/
  ; 
id
  : /[A-Za-z]/ | id /[A-Za-z]/| id decdigit
  ; 
idList
  : id| idList "," id
  ; 
elsedirectiveList
  : "ELSE" dotcomma directiveList
  ;
ifDir
  : ifStatement dotcomma directiveList elseifBlock? elsedirectiveList? "ENDIF" dotcomma
  ; 
ifStatement
  : "IF" constExpr| "IFE" constExpr| "IFB" textItem| "IFNB" textItem| "IFDEF" id| "IFNDEF" id| "IFDIF" textItem "," textItem| "IFDIFI" textItem "," textItem| "IFIDN" textItem "," textItem| "IFIDNI" textItem "," textItem| "IF1" | "IF2" 
  ; 
immExpr
  : expr
  ; 
includeDir
  : "INCLUDE" fileSpec dotcomma
  ; 
includeLibDir
  : "INCLUDELIB" fileSpec dotcomma
  ; 
initValue
  : immExpr| string| "?"| constExpr  "DUP" "(" scalarInstList ")"| floatNumber| bcdConst
  ; 
inSegDir
  :  labelDef?  inSegmentDir
  ; 
inSegDirList
  : inSegDir | inSegDirList inSegDir
  ; 
inSegmentDir
  : instruction| dataDir| controlDir| startupDir| exitDir| offsetDir| labelDir| procDir  localDirList?   inSegDirList?  endpDir| invokeDir| generalDir 
  ; 
instrPrefix
  : "REP" | "REPE" | "REPZ" | "REPNE" | "REPNZ" | "LOCK" 
  ; 
instruction
  :  instrPrefix?  asmInstruction
  ; 
invokeArg
  : register "::" register| expr| "ADDR" expr
  ; 
commainvokeList
  : "," dotcomma? invokeList
  ;
invokeDir
  : "INVOKE" expr commainvokeList? dotcomma
  ; 
invokeList
  : invokeArg| invokeList  "," dotcomma?  invokeArg
  ; 
labelDef
  : id ":" | id "::" | "@@:"
  ; 
labelDir
  : id "LABEL" qualifiedType dotcomma
  ; 
langType
  : "C" | "PASCAL" | "FORTRAN" | "BASIC" | "SYSCALL" | "STDCALL" 
  ; 
listDir
  : listOption dotcomma
  ; 
listOption
  : ".LIST" | ".NOLIST" | ".XLIST" | ".LISTALL" | ".LISTIF" | ".LFCOND" | ".NOLISTIF" | ".SFCOND" | ".TFCOND" | ".LISTMACROALL" | ".LALL" | ".NOLISTMACRO" | ".SALL" | ".LISTMACRO" | ".XALL" 
  ; 
localDef
  : "LOCAL" idList dotcomma
  ; 
localDir
  : "LOCAL" parmList dotcomma
  ; 
localDirList
  : localDir| localDirList localDir
  ; 
localList
  : localDef| localList localDef
  ; 
macroArg
  : "%" constExpr| "%" textMacroId| "%" macroFuncId "(" macroArgList ")"| string| arbitraryText| "<" arbitraryText ">"
  ; 
macroArgList
  : macroArg| macroArgList  "," macroArg
  ; 
macroBody
  :  localList? macroStmtList
  ; 
macroCall
  : id macroArgList dotcomma| id  "(" macroArgList ")"
  ; 
macroDir
  : id "MACRO" macroParmList?  dotcomma macroBody "ENDM" dotcomma
  ; 
macroFor
  : forDir forParm  "," "<" macroArgList ">" dotcomma macroBody "ENDM" dotcomma
  ; 
macroForc
  : forcDir id  "," textLiteral dotcomma macroBody "ENDM" dotcomma
  ; 
macroFuncId
  : id
  ; 
macroId
  : macroProcId| macroFuncId
  ; 
macroIdList
  : macroId| macroIdList  ","  macroId
  ; 
macroLabel
  : id
  ; 
dotdotparmType
  : ":" parmType
  ;
macroParm
  : id dotdotparmType?
  ; 
macroParmList
  : macroParm| macroParmList  "," dotcomma?  macroParm
  ; 
macroProcId
  : id
  ; 
macroRepeat
  : repeatDir constExpr dotcomma macroBody "ENDM" dotcomma
  ; 
macroStmt
  : directive| exitmDir| ":" macroLabel| "GOTO" macroLabel
  ; 
macroStmtList
  : macroStmt dotcomma| macroStmtList macroStmt dotcomma
  ; 
macroWhile
  : "WHILE" constExpr dotcomma macroBody "ENDM" dotcomma
  ; 
mapType
  : "ALL" | "NONE" | "NOTPUBLIC" 
  ; 
memOption
  : "TINY" | "SMALL" | "MEDIUM" | "COMPACT" | "LARGE" | "HUGE" | "FLAT" 
  ; 
mnemonic
  : 
    "aaa"|
    "aad"|
    "aam"|
    "aas"|
    "adc"|
    "add"|
    "and"|
    "cbw"|
    "clc"|
    "cld"|
    "cli"|
    "cmc"|
    "cmp"|
    "cwd"|
    "daa"|
    "das"|
    "dec"|
    "div"|
    "esc"|
    "hlt"|
    "inc"|
    "int"|
    "jae"|
    "jbe"|
    "jge"|
    "jle"|
    "jna"|
    "jnb"|
    "jnc"|
    "jne"|
    "jng"|
    "jnl"|
    "jno"|
    "jnp"|
    "jns"|
    "jnz"|
    "jpe"|
    "jpo"|
    "jmp"|
    "lds"|
    "lea"|
    "les"|
    "mov"|
    "mul"|
    "neg"|
    "nop"|
    "not"|
    "out"|
    "pop"|
    "rcl"|
    "rcr"|
    "ret"|
    "rol"|
    "ror"|
    "sal"|
    "sar"|
    "sbb"|
    "shl"|
    "shr"|
    "stc"|
    "std"|
    "sti"|
    "sub"|
    "xor"|
    "ins"|
    "lar"|
    "lsl"|
    "ltr"|
    "str"|
    "bsf"|
    "bsr"|
    "btc"|
    "btr"|
    "bts"|
    "cdq"|
    "lfs"|
    "lgs"|
    "lss"|
    "ud2"|
    "por"|
    "call"|
    "idiv"|
    "imul"|
    "into"|
    "iret"|
    "jcxz"|
    "jnae"|
    "jnbe"|
    "jnge"|
    "jnle"|
    "lahf"|
    "loop"|
    "popf"|
    "push"|
    "retn"|
    "retf"|
    "sahf"|
    "test"|
    "wait"|
    "xchg"|
    "xlat"|
    "outs"|
    "popa"|
    "arpl"|
    "clts"|
    "lgdt"|
    "lidt"|
    "lldt"|
    "lmsw"|
    "sgdt"|
    "sidt"|
    "sldt"|
    "smsw"|
    "verr"|
    "verw"|
    "cwde"|
    "insb"|
    "insw"|
    "insd"|
    "insq"|
    "seta"|
    "setb"|
    "setc"|
    "sete"|
    "setg"|
    "setl"|
    "seto"|
    "setp"|
    "sets"|
    "setz"|
    "shld"|
    "shrd"|
    "invd"|
    "xadd"|
    "pand"|
    "pxor"|
    "movd"|
    "movq"|
    "emms"|
    "orps"|
    "clgi"|
    "stgi"|
    "dpps"|
    "dppd"|
    "cmpsb"|
    "cmpsw"|
    "jecxz"|
    "lodsb"|
    "lodsw"|
    "lodsd"|
    "loopx"|
    "movsb"|
    "movsw"|
    "pushf"|
    "scasb"|
    "scasw"|
    "stosb"|
    "stosw"|
    "bound"|
    "enter"|
    "leave"|
    "pusha"|
    "cmpsd"|
    "iretb"|
    "iretw"|
    "iretd"|
    "iretq"|
    "loope"|
    "loopz"|
    "movsx"|
    "movsd"|
    "movzx"|
    "popad"|
    "popfd"|
    "scasd"|
    "setae"|
    "setbe"|
    "setge"|
    "setle"|
    "setna"|
    "setnb"|
    "setnc"|
    "setne"|
    "setng"|
    "setnl"|
    "setno"|
    "setnp"|
    "setns"|
    "setnz"|
    "setpe"|
    "setpo"|
    "stosd"|
    "stosq"|
    "bswap"|
    "cpuid"|
    "rdmsr"|
    "rdtsc"|
    "wrmsr"|
    "cmova"|
    "cmovb"|
    "cmovc"|
    "cmove"|
    "cmovg"|
    "cmovl"|
    "cmovo"|
    "cmovp"|
    "cmovs"|
    "cmovz"|
    "rdpmc"|
    "paddb"|
    "paddw"|
    "paddd"|
    "psubb"|
    "psubw"|
    "psubd"|
    "pmull"|
    "pmulh"|
    "pmadd"|
    "pandn"|
    "psllw"|
    "pslld"|
    "psrlw"|
    "psrld"|
    "psraw"|
    "psrad"|
    "psllq"|
    "psrlq"|
    "movss"|
    "addss"|
    "subss"|
    "mulss"|
    "divss"|
    "rcpss"|
    "maxss"|
    "minss"|
    "addps"|
    "subps"|
    "mulps"|
    "divps"|
    "rcpps"|
    "maxps"|
    "minps"|
    "cmpss"|
    "cmpps"|
    "andps"|
    "xorps"|
    "pavgb"|
    "pavgw"|
    "pause"|
    "lddqu"|
    "mwait"|
    "pabsb"|
    "pabsw"|
    "pabsd"|
    "vmxon"|
    "vmrun"|
    "ptest"|
    "crc32"|
    "lzcnt"|
    "loopne"|
    "loopnz"|
    "pushad"|
    "pushfd"|
    "setnae"|
    "setnbe"|
    "setnge"|
    "setnle"|
    "invlpg"|
    "wbinvd"|
    "cmovae"|
    "cmovbe"|
    "cmovge"|
    "cmovle"|
    "cmovna"|
    "cmovnb"|
    "cmovnc"|
    "cmovne"|
    "cmovng"|
    "cmovnl"|
    "cmovno"|
    "cmovnp"|
    "cmovns"|
    "cmovnz"|
    "cmovpe"|
    "cmovpo"|
    "sysret"|
    "paddsb"|
    "paddsw"|
    "psubsb"|
    "psubsw"|
    "movaps"|
    "movups"|
    "movlps"|
    "movhps"|
    "sqrtss"|
    "sqrtps"|
    "comiss"|
    "shufps"|
    "andnps"|
    "psadbw"|
    "pmaxub"|
    "pminub"|
    "pmaxsw"|
    "pminsw"|
    "pextrw"|
    "pinsrw"|
    "pshufw"|
    "movntq"|
    "sfence"|
    "lfence"|
    "mfence"|
    "movnti"|
    "haddpd"|
    "haddps"|
    "hsubpd"|
    "hsubps"|
    "psignb"|
    "psignw"|
    "psignd"|
    "pshufb"|
    "phsubw"|
    "phsubd"|
    "phaddw"|
    "phaddd"|
    "vmread"|
    "vmcall"|
    "vmxoff"|
    "skinit"|
    "vmload"|
    "vmsave"|
    "rdtscp"|
    "pmuldq"|
    "pmulld"|
    "pminsb"|
    "pmaxsb"|
    "pminuw"|
    "pmaxuw"|
    "pminud"|
    "pmaxud"|
    "pminsd"|
    "pmaxsd"|
    "pinsrb"|
    "pinsrd"|
    "pinsrq"|
    "pextrb"|
    "pextrd"|
    "pextrq"|
    "popcnt"|
    "loadall"|
    "cmpxchg"|
    "cmovnae"|
    "cmovnbe"|
    "cmovnge"|
    "cmovnle"|
    "sysexit"|
    "syscall"|
    "paddusb"|
    "paddusw"|
    "psubusb"|
    "psubusw"|
    "pcmpeqb"|
    "pcmpeqw"|
    "pcmpeqd"|
    "movlhps"|
    "movhlps"|
    "rsqrtss"|
    "rsqrtps"|
    "ucomiss"|
    "pmulhuw"|
    "ldmxcsr"|
    "stmxcsr"|
    "movntps"|
    "clflush"|
    "movntdq"|
    "movntpd"|
    "movddup"|
    "fisfttp"|
    "monitor"|
    "palignr"|
    "phaddsw"|
    "vmptrld"|
    "vmptrst"|
    "vmclear"|
    "vmwrite"|
    "vmmcall"|
    "mpsadbw"|
    "blendps"|
    "blendpd"|
    "pblendw"|
    "roundps"|
    "roundss"|
    "roundpd"|
    "roundsd"|
    "pcmpeqq"|
    "pcmpgtq"|
    "sysenter"|
    "pcmpgtpb"|
    "pcmpgtpw"|
    "pcmpgtpd"|
    "packsswb"|
    "packssdw"|
    "packuswb"|
    "unpckhps"|
    "unpcklps"|
    "cvtsi2ss"|
    "cvtss2si"|
    "cvtpi2ps"|
    "cvtps2pi"|
    "pmovmskb"|
    "maskmovq"|
    "addsubpd"|
    "addsubps"|
    "movshdup"|
    "movsldup"|
    "pmulhrsw"|
    "vmlaunch"|
    "vmresume"|
    "blendvps"|
    "blendvpd"|
    "pblendvb"|
    "insertps"|
    "pmovsxbw"|
    "pmovzxbw"|
    "pmovsxbd"|
    "pmovzxbd"|
    "pmovsxbq"|
    "pmovzxbq"|
    "pmovsxwd"|
    "pmovzxwd"|
    "pmovsxwq"|
    "pmovzxwq"|
    "pmovsxdq"|
    "pmovzxdq"|
    "packusdw"|
    "movntdqa"|
    "cmpxchg8b"|
    "punpckhbw"|
    "punpckhwd"|
    "punpckhdq"|
    "punpcklbw"|
    "punpcklwd"|
    "punpckldq"|
    "cvttss2si"|
    "cvttps2pi"|
    "prefetch0"|
    "prefetch1"|
    "prefetch2"|
    "pmaddubsw"|
    "extractps"|
    "pcmpestri"|
    "pcmpestrm"|
    "pcmpistri"|
    "pcmpistrm"|
    "maskmovdqu"|
    "cmpxchg16b"|
    "phminposuw"|
    "prefetchnta"|

    "f2xm1"|
    "FABS"|
    "fadd"|
    "faddp"|
    "fbld"|
    "fbstp"|
    "fchs"|
    "fclex"|
    "fcom"|
    "fcomp"|
    "fcompp"|
    "fdecstp"|
    "fdisi"|
    "fdiv"|
    "fdivp"|
    "fdivr"|
    "fdivrp"|
    "feni"|
    "ffree"|
    "fiadd"|
    "ficom"|
    "ficomp"|
    "fidiv"|
    "fidivr"|
    "fild"|
    "fimul"|
    "fincstp"|
    "finit"|
    "fist"|
    "fistp"|
    "fisub"|
    "fisubr"|
    "fld"|
    "fld1"|
    "fldcw"|
    "fldenv"|
    "fldenvw"|
    "fldl2e"|
    "fldl2t"|
    "fldlg2"|
    "fldln2"|
    "fldpi"|
    "fldz"|
    "fmul"|
    "fmulp"|
    "fnclex"|
    "fndisi"|
    "fneni"|
    "fninit"|
    "fnop"|
    "fnsave"|
    "fnsavew"|
    "fnstcw"|
    "fnstenv"|
    "fnstenvw"|
    "fnstsw"|
    "fpatan"|
    "fprem"|
    "fptan"|
    "frndint"|
    "frstor"|
    "frstorw"|
    "fsave"|
    "fsavew"|
    "fscale"|
    "fsqrt"|
    "fst"|
    "fstcw"|
    "fstenv"|
    "fstenvw"|
    "fstp"|
    "fstsw"|
    "fsub"|
    "fsubp"|
    "fsubr"|
    "fsubrp"|
    "ftst"|
    "fwait"|
    "fxam"|
    "fxch"|
    "fxtract"|
    "fyl2x"|
    "fyl2xp1"|
    "fsetpm"|
    "fcos"|
    "fldenvd"|
    "fnsaved"|
    "fnstenvd"|
    "fprem1"|
    "frstord"|
    "fsaved"|
    "fsin"|
    "fsincos"|
    "fstenvd"|
    "fucom"|
    "fucomp"|
    "fucompp"|
    "fcmovbe"|
    "fcmove"|
    "fcmovnb"|
    "fcmovnbe"|
    "fcmovne"|
    "fcmovnu"|
    "fcmovu"|
    "fcomip"|
    "fucomi"|
    "fucomip"|
    "fxrstor"|
    "fxrstorb"|
    "fxrstorw"|
    "fxrstorq"|
    "fxsave"|
    "fxsaveb"|
    "fxsavew"|
    "fxsaveq"|
    "ffreep"|


    "movdqa"|
    "movdqu"|
    "movapd"|
    "movupd"|

    "psrldq"|
    "pslldq"|
    "pshufd"|
    "pshuflw"|
    "shufpd"|

    "pmullw"|
    "pmulhw"|
    "pmuludq"|
    "punpcklqdq"|
    "punpckhqdq"|
    "paddq"|
    "pcmpgtd"|
    "psubq"|
    "movdq2q"
  ; 
commamodelOptlist
  : "," modelOptlist
  ;
modelDir
  : ".MODEL" memOption commamodelOptlist? dotcomma
  ; 
modelOpt
  : langType| stackOption 
  ; 
modelOptlist
  : modelOpt| modelOptlist  "," modelOpt
  ; 
module
  :  directiveList?  endDir
  ; 
mulOp
  : "*"| "/" | "MOD" 
  ; 
nameDir
  : "NAME" id dotcomma
  ; 
nearfar
  : "NEAR" | "FAR" 
  ; 
nestedStruct
  : structHdr  id?  dotcomma structBody "ENDS" dotcomma
  ; 
offsetDir
  : offsetDirType dotcomma
  ; 
offsetDirType
  : "EVEN" | "ORG" immExpr| "ALIGN" constExpr? 
  ; 
offsetType
  : "GROUP" | "SEGMENT" | "FLAT" 
  ; 
oldRecordFieldList
  :  constExpr? | oldRecordFieldList ","  constExpr? 
  ; 
optionDir
  : "OPTION" optionList dotcomma
  ; 
readonly
  : "READONLY"
  ;
optionItem
  : "CASEMAP" ":" mapType| "DOTNAME" | "NODOTNAME" | "EMULATOR" | "NOEMULATOR" | "EPILOGUE" ":" macroId| "EXPR16" | "EXPR32" | "LANGUAGE" ":" langType| "LJMP" | "NOLJMP" | "M510" | "NOM510" | "NOSIGNEXTEND" | "OFFSET" ":" offsetType| "OLDMACROS" | "NOOLDMACROS" | "OLDSTRUCTS" | "NOOLDSTRUCTS" | "PROC" ":" oVisibility| "PROLOGUE" ":" macroId| readonly | "NOREADONLY" | "SCOPED" | "NOSCOPED" | "SEGMENT" ":" segSize| "SETIF2" ":" bool
  ; 
optionList
  : optionItem| optionList  "," dotcomma?  optionItem
  ; 
optText
  : "," textItem
  ; 
orOp
  : "OR" | "XOR" 
  ; 
oVisibility
  : "PUBLIC" | "PRIVATE" | "EXPORT" 
  ; 
pageDir
  : "PAGE" pageExpr?  dotcomma
  ; 
commapageWidth
  : "," pageWidth
  ;
pageExpr
  : "+"|  pageLength?  commapageWidth?
  ; 
pageLength
  : constExpr
  ; 
pageWidth
  : constExpr
  ; 
dotdotqualifiedType
  : ":" qualifiedType
  ;
parm
  : parmId dotdotqualifiedType? | parmId  constExpr? dotdotqualifiedType?
  ; 
parmId
  : id
  ; 
parmList
  : parm| parmList  "," dotcomma?  parm
  ; 
parmType
  : "REQ" | "=" textLiteral| "VARARG" 
  ; 
pOptions
  :  distance?   langType?   oVisibility? 
  ; 
primary
  : expr binaryOp expr| flagName| expr
  ; 
brmacroArgList
  : "<" macroArgList ">"
  ;
procDir
  : procId "PROC" pOptions?  brmacroArgList?  usesRegs?   procParmList? 
  ; 
processor
  : ".8086" | ".186" | ".286" | ".286C" | ".286P" | ".386" | ".386C" | ".386P" | ".486" | ".486P" | ".586" | ".586P" |
 ".686" | ".686P" | ".K3D" | ".MMX" | ".XMM" | ".8086" 
  ; 
processorDir
  : processor dotcomma | coprocessor dotcomma
  ; 
procId
  : id
  ; 
commaparmList
  : ","  dotcomma?  parmList
  ;
commaparmIdvararg
  : ","  dotcomma?  parmId ":VARARG" 
  ;
procParmList
  : commaparmList? 
    commaparmIdvararg?
  ; 
protoArg 
  :  id? ":" qualifiedType 
  ; 
commaprotoList
  : ","  dotcomma?  protoList
  ;
commaidvararg
  : ","  dotcomma?   id? ":VARARG" 
  ;
protoArgList
  : commaprotoList?
    commaidvararg?
  ; 
protoList
  : protoArg| protoList  "," dotcomma?  protoArg
  ; 
protoSpec
  :  distance?   langType?   protoArgList?  | typeId
  ; 
protoTypeDir
  : id "PROTO" protoSpec
  ; 
pubDef
  :  langType?  id
  ; 
publicDir
  : "PUBLIC" pubList dotcomma
  ; 
pubList
  : pubDef| pubList  "," dotcomma?  pubDef
  ; 
purgeDir
  : "PURGE" macroIdList
  ; 
qualifiedType
  : type|  distance? "PTR" qualifiedType? 
  ; 
qualifier
  : qualifiedType| "PROTO" protoSpec
  ; 
quote
  : '"' | "'"
  ; 
radixDir
  : ".RADIX" constExpr dotcomma
  ; 
radixOverride
  : /[hoqtyHOQTY]/
  ; 
recordConst
  : recordTag "{" oldRecordFieldList "}"| recordTag "<" oldRecordFieldList ">"
  ; 
recordDir
  : recordTag "RECORD" bitDefList dotcomma 
  ; 
recordFieldList
  :  constExpr? | recordFieldList  ","  dotcomma?   constExpr? 
  ; 
recordInstance
  : "{"  dotcomma?  recordFieldList  dotcomma?  "}"| "<" oldRecordFieldList ">"| constExpr "DUP" "(" recordInstance ")"
  ; 
recordInstList
  : recordInstance| recordInstList ","  dotcomma?  recordInstance
  ; 
recordTag
  : id
  ; 
register
  : specialRegister| gpRegister| byteRegister
  ; 
regList
  : register| regList register
  ; 
relOp
  : "EQ" | "NE" | "LT" | "LE" | "GT" | "GE" 
  ; 
repeatBlock
  : ".REPEAT" dotcomma blockStatements dotcomma untilDir dotcomma
  ; 
repeatDir
  : "REPEAT" | "REPT" 
  ; 
scalarInstList
  : initValue| scalarInstList  ","  dotcomma?  initValue
  ; 
segAlign
  : "BYTE" | "WORD" | "DWORD" | "PARA" | "PAGE" 
  ; 
segAttrib
  : "PUBLIC" | "STACK" | "COMMON" | "MEMORY" | "AT" constExpr| "PRIVATE" 
  ; 
segDir
  : ".CODE" segId? | ".DATA" | ".DATA?"| ".CONST" | ".FARDATA" segId? | ".FARDATA?" segId? | ".STACK" constExpr? 
  ; 
segId
  : id
  ; 
segIdList 
  : segId| segIdList  "," segId
  ; 
segmentDef
  : segmentDir  inSegDirList?  endsDir| simpleSegDir  inSegDirList?   endsDir? 
  ; 
segmentDir
  : segId "SEGMENT" segOptionList?  dotcomma
  ; 
segmentRegister
  : 'CS' | 'DS' | 'ES' | 'FS' | 'GS' | 'SS'
  ; 
segOption
  : segAlign| segRO| segAttrib| segSize| className
  ; 
segOptionList
  : segOption| segOptionList segOption
  ; 
segOrderDir
  : ".ALPHA" | ".SEQ" | ".DOSSEG" | "DOSSEG" 
  ; 
segRO
  : readonly
  ; 
segSize 
  : "USE16" | "USE32" | "FLAT" 
  ; 
shiftOp
  : "SHR" | "SHL" 
  ; 
sign
  : "-" | "+"
  ; 
simpleExpr
  : "(" cExpr ")"| primary
  ; 
simpleSegDir
  : segDir dotcomma
  ; 
sizeArg
  : id| type| e10
  ; 
specialChars
  : ":" | "." | "[[" | "]]" | "(" | ")" | "<" | ">" | "{" | "}"| "+" | "-" | "/" | "*" | "&" | "%" | "!"| "'" | "\\" | "=" | ";" | "," | '"'| whiteSpaceCharacter | endOfLine
  ; 
specialRegister
  : 'CR0' | 'CR2' | 'CR3' | 'DR0' | 'DR1' | 'DR2' | 'DR3' | 'DR6' | 'DR7'| 'TR3' | 'TR4' | 'TR5' | 'TR6' | 'TR7'
  ; 
stackOption
  : "NEARSTACK" | "FARSTACK" 
  ; 
startupDir
  : ".STARTUP" dotcomma
  ; 
stext
  : stringChar| stext stringChar
  ; 
string
  : quote  stext?  quote
  ; 
stringChar
  : quote quote| /[^\'\"]/
  ; 
structBody
  : structItem dotcomma | structBody structItem dotcomma
  ; 
commanonuniq
  : "," "NONUNIQUE"
  ;
structDir
  : structTag structHdr  fieldAlign?  commanonuniq? dotcomma structBody structTag "ENDS" dotcomma
  ; 
structHdr
  : "STRUC" | "STRUCT" | "UNION" 
  ; 
structInstance
  : "<"  fieldInitList?  ">"| "{" dotcomma?   fieldInitList?   dotcomma?  "}"| constExpr "DUP" "(" structInstList ")"
  ; 
structInstList
  : structInstance| structInstList  ","  dotcomma?  structInstance
  ; 
structItem 
  : dataDir| generalDir| offsetDir| nestedStruct
  ; 
structTag
  : id
  ; 
term
  : simpleExpr| "!" simpleExpr
  ; 
text
  : textLiteral| text character| "!" character text| character| "!" character
  ; 
textDir
  : id textMacroDir dotcomma
  ; 
textItem
  : textLiteral| textMacroId| "%" constExpr
  ; 
textLen
  : constExpr
  ; 
textList
  : textItem| textList  "," dotcomma?  textItem
  ; 
textLiteral
  : "<" text ">" dotcomma
  ; 
commatextLen
  : "," textLen
  ;
textStartcomma
  : textStart  ","
  ;
textMacroDir
  : "CATSTR" textList? | "TEXTEQU" textList? | "SIZESTR" textItem| "SUBSTR" textItem  "," textStart commatextLen| "INSTR" textStartcomma? textItem  "," textItem
  ; 
textMacroId
  : id
  ; 
textStart
  : constExpr
  ; 
titleDir
  : titleType arbitraryText dotcomma
  ; 
titleType
  : "TITLE" | "SUBTITLE" | "SUBTTL" 
  ; 
type
  : structTag| unionTag| recordTag| distance| dataType| typeId
  ; 
typedefDir
  : typeId "TYPEDEF" qualifier
  ; 
typeId
  : id
  ; 
unionTag
  : id
  ; 
untilDir
  : ".UNTIL" cExpr dotcomma ".UNTILCXZ" cxzExpr?  dotcomma
  ; 
usesRegs
  : "USES" regList 
  ; 
whileBlock
  : ".WHILE" cExpr dotcomma blockStatements dotcomma ".ENDW" 
  ; 
whiteSpaceCharacter
  : /[\b\t\v\f\r\x1a\s]/
  ;
